apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_PASSWORD: "postgres"  # Should match Postgres secret
  JWT_SECRET: "your-jwt-secret-here"
  # maybe we will need to add more later