apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner-role
rules:
  - apiGroups: ["*"]
    resources: ["pods", "pods/exec", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner-binding
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-ci
roleRef:
  kind: ClusterRole
  name: gitlab-runner-role
  apiGroup: rbac.authorization.k8s.io