apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-secret-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarkus-secret-reader-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quarkus-secret-reader
subjects:
  - kind: ServiceAccount
    name: quarkus-app
    namespace: default