version: '0.1'

services:

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
    networks:
      - rabbitmq-elasticsearch-network

  producer:
    image: elastic-adapter-producer:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: elastic-adapter-producer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    networks:
      - rabbitmq-elasticsearch-network

  processor:
    image: elastic-adapter:0.1-${QUARKUS_MODE:-jvm}
    build:
      context: elastic-adapter
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    networks:
      - rabbitmq-elasticsearch-network

networks:
  rabbitmq-elasticsearch-network:
    name: elastic-adapter